# Generated by Django 5.0.6 on 2024-10-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioxx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residente',
            name='apellido',
            field=models.CharField(max_length=80),
        ),
    ]
