# Generated by Django 5.0.6 on 2024-10-25 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dioxx', '0002_alter_residente_apellido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallereceta',
            name='idMedicamento',
        ),
        migrations.RemoveField(
            model_name='detallereceta',
            name='idReceta',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='residente',
        ),
        migrations.DeleteModel(
            name='medicamento',
        ),
        migrations.DeleteModel(
            name='detalleReceta',
        ),
        migrations.DeleteModel(
            name='receta',
        ),
        migrations.DeleteModel(
            name='residente',
        ),
    ]
