# Generated by Django 5.0.6 on 2024-10-26 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dioxx', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallereceta',
            name='idMedicamento',
        ),
        migrations.RemoveField(
            model_name='detallereceta',
            name='idReceta',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='residente',
        ),
        migrations.DeleteModel(
            name='medicamento',
        ),
        migrations.DeleteModel(
            name='detalleReceta',
        ),
        migrations.DeleteModel(
            name='receta',
        ),
        migrations.DeleteModel(
            name='residente',
        ),
    ]
