# Generated by Django 5.0.6 on 2024-10-26 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dioxx', '0005_remove_detallereceta_idmedicamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cargoPersonal',
            fields=[
                ('idCargo', models.CharField(db_column='idCargo', max_length=6, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='medicamento',
            fields=[
                ('idMedicamento', models.AutoField(db_column='idMedicamento', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='receta',
            fields=[
                ('idReceta', models.AutoField(db_column='idReceta', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='residente',
            fields=[
                ('rut', models.CharField(db_column='rut', max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('edad', models.IntegerField()),
                ('contactos', models.CharField(max_length=30)),
                ('nroEmergencia', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='personal',
            fields=[
                ('rut', models.CharField(db_column='rut', max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('cargo', models.ForeignKey(db_column='idCargo', on_delete=django.db.models.deletion.CASCADE, to='dioxx.cargopersonal')),
            ],
        ),
        migrations.CreateModel(
            name='detalleReceta',
            fields=[
                ('idDetalleR', models.AutoField(db_column='idDetalleR', primary_key=True, serialize=False)),
                ('cantDosis', models.IntegerField()),
                ('horario', models.CharField(max_length=20)),
                ('idMedicamento', models.ForeignKey(db_column='idMedicamento', on_delete=django.db.models.deletion.CASCADE, to='dioxx.medicamento')),
                ('idReceta', models.ForeignKey(db_column='idReceta', on_delete=django.db.models.deletion.CASCADE, to='dioxx.receta')),
            ],
        ),
        migrations.AddField(
            model_name='receta',
            name='residente',
            field=models.ForeignKey(db_column='rut', on_delete=django.db.models.deletion.CASCADE, to='dioxx.residente'),
        ),
    ]
