# Generated by Django 5.0.6 on 2024-10-26 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dioxx', '0015_delete_acceso_remove_personal_cargo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='acceso',
            fields=[
                ('idAcceso', models.AutoField(db_column='idAcceso', primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=20)),
                ('personaRut', models.CharField(max_length=12)),
                ('personaNombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='cargoPersonal',
            fields=[
                ('idCargo', models.CharField(db_column='idCargo', max_length=6, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='evento',
            fields=[
                ('idEvento', models.AutoField(db_column='idEvento', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='medicamento',
            fields=[
                ('idMedicamento', models.AutoField(db_column='idMedicamento', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='notificacion',
            fields=[
                ('idNotificacion', models.AutoField(db_column='idNotificacion', primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='receta',
            fields=[
                ('idReceta', models.AutoField(db_column='idReceta', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='residente',
            fields=[
                ('rut', models.CharField(db_column='rut', max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('edad', models.IntegerField()),
                ('contactos', models.CharField(max_length=30)),
                ('nroEmergencia', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Dosis',
            fields=[
                ('idDosis', models.AutoField(db_column='idDosis', primary_key=True, serialize=False)),
                ('horario', models.CharField(choices=[('m', 'Mañana'), ('t', 'Tarde'), ('n', 'Noche')], max_length=1)),
                ('cantidad', models.PositiveIntegerField()),
                ('administrada', models.BooleanField(default=False)),
                ('medicamento', models.ForeignKey(db_column='idMedicamento', on_delete=django.db.models.deletion.CASCADE, to='dioxx.medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='personal',
            fields=[
                ('rut', models.CharField(db_column='rut', max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('cargo', models.ForeignKey(db_column='idCargo', on_delete=django.db.models.deletion.CASCADE, to='dioxx.cargopersonal')),
            ],
        ),
        migrations.CreateModel(
            name='detalleReceta',
            fields=[
                ('idDetalleR', models.AutoField(db_column='idDetalleR', primary_key=True, serialize=False)),
                ('cantDosis', models.IntegerField()),
                ('horario', models.CharField(max_length=20)),
                ('idMedicamento', models.ForeignKey(db_column='idMedicamento', on_delete=django.db.models.deletion.CASCADE, to='dioxx.medicamento')),
                ('idReceta', models.ForeignKey(db_column='idReceta', on_delete=django.db.models.deletion.CASCADE, to='dioxx.receta')),
            ],
        ),
        migrations.AddField(
            model_name='receta',
            name='residente',
            field=models.ForeignKey(db_column='rut', on_delete=django.db.models.deletion.CASCADE, to='dioxx.residente'),
        ),
        migrations.CreateModel(
            name='emergencia',
            fields=[
                ('idEmergencia', models.AutoField(db_column='idEmergencia', primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=1000)),
                ('residente', models.ForeignKey(db_column='rut', on_delete=django.db.models.deletion.CASCADE, to='dioxx.residente')),
            ],
        ),
    ]
