# Generated by Django 5.0 on 2024-11-06 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dioxx', '0016_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='acceso',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='detallereceta',
            name='idMedicamento',
        ),
        migrations.RemoveField(
            model_name='detallereceta',
            name='idReceta',
        ),
        migrations.RemoveField(
            model_name='dosis',
            name='medicamento',
        ),
        migrations.RemoveField(
            model_name='emergencia',
            name='residente',
        ),
        migrations.DeleteModel(
            name='evento',
        ),
        migrations.DeleteModel(
            name='notificacion',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='residente',
        ),
        migrations.DeleteModel(
            name='cargoPersonal',
        ),
        migrations.DeleteModel(
            name='personal',
        ),
        migrations.DeleteModel(
            name='detalleReceta',
        ),
        migrations.DeleteModel(
            name='Dosis',
        ),
        migrations.DeleteModel(
            name='medicamento',
        ),
        migrations.DeleteModel(
            name='emergencia',
        ),
        migrations.DeleteModel(
            name='receta',
        ),
        migrations.DeleteModel(
            name='residente',
        ),
    ]
